### ISSUE TITLE
Dataset link

### ISSUE THREAD

**Issue by yeldarby** [myatmyintzuthin/aquarium_object_detection#1]
Neat project! Could you link back to [the original source](https://public.roboflow.com/object-detection/aquarium) for the dataset? I collected it & someone just re-hosted it on Kaggle.

**Comment by myatmyintzuthin** [comment]
Hello, @yeldarby. I'm sorry for the inconvenience. I linked back to the original dataset in my repository. Thank you so much for collecting such a good dataset. It really helped me a lot in my learning.
